spring:
  main:
    web-application-type: none
    allow-bean-definition-overriding: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.0.31:8092
          zk-nodes: 192.168.0.31
      bindings:
        input:
          binder: kafka
          destination: textToNER
        output:
          binder: kafka
          destination: textToNER
format: dd/MM/YYYY hh:mm:ss
fixed-delay: 3000
urlner: http://192.168.0.31:9999/opener
urlinsight:  http://192.168.0.31:8080/api/
urlgeotrouvethon: http://192.168.0.31:9966/locate/
ner:  true
graph:
  enabled: true
elasticsearch:
  enabled: true
  host: 192.168.0.31
  clustername: insight
  port: 9200
  node-port: 9200
  index-name: gazetter