version: '3'
services:
    #BROKER
    zookeeper:
        image: wurstmeister/zookeeper:latest
        ports:
          - 2181:2181
    kafka:
        image: wurstmeister/kafka:latest
        container_name: kafka
        environment:
          KAFKA_ADVERTISED_HOST_NAME: 192.168.0.31
          KAFKA_ADVERTISED_PORT: 8092
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_CREATE_TOPICS: "housToGoogle:1:1,housToTwit:1:1,housToTravel:1:1,housToCompara:1:1,urlToScrapy:1:1,googleToTwit:1:1,textToNER:1:1,tweetToColissi:1:1,tweetToCrousti:1:1,ggimgToColissi:1:1,locToColissi:1:1,bioToColissi:1:1,orgaToColissi:1:1,mediaToColissi:1:1"
        ports:
          - 8092:9092
    #NER
    wrapper:
        image: cwolff/opener-docker-wrapper
        build:
          context: ./wrapper
        environment:
          SANIC_OPENER_IDENTIFY_LANGUAGE_URL: http://language_identifier
          SANIC_OPENER_TOKENIZE_URL: http://tokenizer
          SANIC_OPENER_POS_URL: http://pos_tagger
          SANIC_OPENER_NER_URL: http://ner
          SANIC_OPENER_KAF2JSON_URL: http://kaf2json
        ports:
          - 9999:80
        depends_on:
          - language_identifier
          - tokenizer
          - pos_tagger
          - ner
          - kaf2json

    language_identifier:
        image: cwolff/opener-docker-language-identifier

    tokenizer:
        image: cwolff/opener-docker-tokenizer

    pos_tagger:
        image: cwolff/opener-docker-pos-tagger

    ner:
        image: cwolff/opener-docker-ner

    kaf2json:
        image: cwolff/opener-docker-kaf2json